### ISSUE TITLE
BGM毎回探すのが大変な件

### ISSUE THREAD

**Issue by masatakashiwagi** [double-m2ml/podcast.fm#39]
## 提案 or 困り事
- [ ] 提案
- [x] 困り事

## 内容
- BGMをEvoke Musicで毎回良い感じのものを探すのが大変

## 提案内容
- 音源も溜まってきたので，1ヶ月単位で変更するのはどうか
- コーヒーブレイクと本編でBGMを分けるはどうか
    - コーヒーブレイクの方は固定で本編のBGMを1ヶ月単位で変更

**Comment by masatakashiwagi** [comment]
@navitacion 
こちらどうですかね？
最近BGM探すの大変だなーと思ったので，1ヶ月は固定でも良いのかなと思いました．

**Comment by navitacion** [comment]
そうっすね！確かに大変ですよね、、！
ストックも貯まってきたので、ローテーションで回していってもいいかもです

**Comment by masatakashiwagi** [comment]
では，今回からちょっとトライしてみますねー！

**Comment by navitacion** [comment]
BGMを分けるのもいいと思いますが、編集大変じゃないですか？？
この辺は編集者の好みに合わせちゃってもいいのかなーと思います！

**Comment by masatakashiwagi** [comment]
確かに，それもそうですねー！
> この辺は編集者の好みに合わせちゃってもいいのかなーと思います！

それではそんな感じでいきましょー！
