### ISSUE TITLE
Notionの活用

### ISSUE THREAD

**Issue by masatakashiwagi** [double-m2ml/podcast.fm#76]
## 提案 or 困り事
- [x] 提案
- [ ] 困り事

## 内容
- Scrapboxもいいけど，最近流行りのNotion使ってみるのはどうか？
    - ドキュメント管理がよりしやすくなるかなと思い
- 来年から使うのはどうか？

**Comment by navitacion** [comment]
あ、こちらご提案ありがとうございます！！
すっかり返事忘れてました。。すみません。。

Notion使ってみるのアリですね！
Scrapboxだとマークダウンがうまく機能しないのがうーんという感じでした

**Comment by masatakashiwagi** [comment]
コメントありがとうございます😊
Notion会社で使い出していいなーと思っていて、テンプレート化とか管理がやり易いのでこっちでも使えたらと思います笑

次回とか軽く話せたらと！

**Comment by masatakashiwagi** [comment]
ちなみに，naviさんは社内でもNotion使ってたりしますか？

**Comment by masatakashiwagi** [comment]
いい感じに使い出せてるので，このIssueはcloseします！
